blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>', views.blogs_with_type,
         name='blogs_with_type')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditot', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import login
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    # 登陆页面
    path('login/', login, 'users/login.html', name='login')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField


class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name


class Blog(models.Model):
    title = models.CharField(max_length=50)
    content = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete='DO_NOTHING')
    created_time = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now=True)
    read_num = models.IntegerField(default=0)
    blog_type = models.ForeignKey('BlogType', on_delete='DO_NOTHING')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_time']

users/models.py
from django.db import models

# Create your models here.

blog/views.py
from datetime import datetime

from django.shortcuts import render
from django.core.paginator import Paginator

from blog.models import BlogType, Blog


def home(request):
    context = {}
    return render(request, 'blog/home.html', context)


def blog_list(request):
    contact_list = Blog.objects.all()
    paginator = Paginator(contact_list, 2)

    page = request.GET.get('page')
    contacts = paginator.get_page(page)

    return render(request, 'blog/blog_list.html',
                  {'paginator': paginator,
                   'contacts': contacts, }
                  )


def blog_detail(request, blog_pk):
    blog = Blog.objects.get(pk=blog_pk)

    # 设置cookie
    if not request.COOKIES.get(f'blog_{blog_pk}_read'):
        blog.read_num += 1
        blog.save()

    previous_blog = Blog.objects.filter(
        created_time__gt=blog.created_time).last()
    next_blog = Blog.objects.filter(created_time__lt=blog.created_time).first()
    context = {'blog': blog,
               'previous_blog': previous_blog,
               'next_blog': next_blog
               }
    response = render(request, 'blog/blog_detail.html', context)
    response.set_cookie(f'blog_{blog_pk}_read', True, max_age=60)
    return response


def blogs_with_type(request, blog_type_pk):
    blog_type = BlogType.objects.get(pk=blog_type_pk)
    type_blogs = Blog.objects.filter(blog_type__pk=blog_type_pk)

    context = {'blogs': type_blogs, 'blog_type': blog_type}
    return render(request, 'blog/blogs_with_type.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/blog/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
  <meta name="format-detection" content="telephone=no"/>
  <meta charset="utf-8">

  <title>我的网站|首页</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>

<body>


<nav class="navbar navbar-default navbar-static-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">
        个人博客网站</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'home' %}">首页</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-collapse-right">
        <li><a href="{% url 'blog_list' %}">博客列表</a></li>
      </ul>

      <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
          欢迎, {{ user.username }}
        {% else %}
          <a href="{% url 'users:login' %}">登陆</a>
        {% endif %}
      </ul>

    </div>

  </div>
</nav>

<div class="container">

  <div class="page-header">
    {% block header %}{% endblock %}
  </div>
  <div>
    {% block content %}{% endblock %}
  </div>

</div>

</body>
</html>

templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% block header %}
  {{ blog.title }}
{% endblock %}

{% block content %}
  <p>
    分类: <a href="{% url 'blogs_with_type' blog.blog_type.pk %}">
    {{ blog.blog_type }}</a>
  </p>
  <h3>{{ blog.title }}</h3>
  <p>{{ blog.content|safe }}</p>
  <br>

  <p align="right">作者: {{ blog.author }}</p>
  <p align="right">发表时间: {{ blog.created_time|date:'Y-m-d H:n:s' }}</p>
  <p align="right">阅读数量: {{ blog.read_num }}</p>
  <div class="blog-more">
    {% if previous_blog %}
      <a href="{% url 'blog_detail' previous_blog.pk %}">
        <p>
          上一篇: {{ previous_blog.title }}
        </p>
      </a>
    {% else %}
      <p>已经是第一篇了</p>
    {% endif %}
    {% if next_blog %}
      <a href="{% url 'blog_detail' next_blog.pk %}">
        <p>
          下一篇: {{ next_blog.title }}
        </p>
      </a>
    {% else %}
      <p>已经是最后一篇了</p>
    {% endif %}


  </div>
{% endblock %}

templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% block header %}
  我的博客
{% endblock %}

{% block content %}
  <p>一共有{{ contacts|length }}篇博客</p>

  {% for blog in contacts %}
    <a href="{% url 'blog_detail' blog.pk %}">
      <h3>{{ blog.title }}----{{ blog.blog_type.type_name }}</h3>
    </a>
    <p>{{ blog.content|striptags|truncatechars:30 }}</p>
    <p>阅读数量: {{ blog.read_num }}</p>
  {% empty %}
    <p>说点啥吧</p>
  {% endfor %}

  <div class="pagination">
    <div class="step-links">

      <div aria-label="Page navigation">
        <ul class="pagination">

          <li>
            {% if contacts.has_previous %}
              <a href="?page=1">&laquo; 首页</a>
              <a href="?page={{ contacts.previous_page_number }}">上一页</a>
            {% endif %}
          </li>

          {% for page_number in paginator.page_range %}
            {% if page_number == contacts.number %}
              <li class="active"><a href="?page={{ page_number }}"
              >{{ page_number }}</a></li>
            {% else %}
              <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %}
          {% endfor %}

          <li>
            {% if contacts.has_next %}
              <a href="?page={{ contacts.next_page_number }}">下一页</a>
              <a href="?page={{ contacts.paginator.num_pages }}">尾页 &raquo;</a>
            {% endif %}

          <li>
            第 {{ contacts.number }} 页 共 {{ contacts.paginator.num_pages }} 页
          </li>

        </ul>
      </div>

    </div>
  </div>
{% endblock %}

templates/blog/blogs_with_type.html
{% extends 'blog/base.html' %}
{% block header %}
  {{ blog_type.type_name }}
{% endblock %}

{% block content %}
  <p>一共有{{ blogs|length }}篇博客</p>
  <h3>{{ blog_type.type_name }}</h3>

  {% for blog in blogs %}
    <a href="{% url 'blog_detail' blog.pk %}">
      <h3>{{ blog.title }}</h3>
    </a>
    <p>{{ blog.content|truncatechars:30 }}</p>
  {% empty %}
    <p>说点啥吧</p>
  {% endfor %}
{% endblock %}

templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}
  我的网站|首页
{% endblock %}
<link rel="stylesheet" href="/static/css/home.css">
{% block header_extends %}

{% endblock %}

{% block content %}
  <h3 class="home-context">欢迎访问</h3>

{% endblock %}

templates/users/login.html
{% extends 'blog/base.html' %}

{% block content %}

  {% if form.errors %}
    <p>用户名或密码错误</p>
  {% endif %}

  <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">登陆</button>
    <input type="hidden" name="next" value="{% url 'blog_list' %}">
  </form>

{% endblock content %}